// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp50kUKBQhPyawY24cMEYbKL_QNZ_9mvg',
    appId: '1:532983348001:web:a8a38836f2964cf976dc60',
    messagingSenderId: '532983348001',
    projectId: 'reminderapp-6ffe3',
    authDomain: 'reminderapp-6ffe3.firebaseapp.com',
    storageBucket: 'reminderapp-6ffe3.appspot.com',
    measurementId: 'G-G3MF0K6FVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXvL2hXi7TLTaiQZDzbcU_ttY__yqvdSM',
    appId: '1:532983348001:android:8df447f240cbc6f676dc60',
    messagingSenderId: '532983348001',
    projectId: 'reminderapp-6ffe3',
    storageBucket: 'reminderapp-6ffe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB56eLI1PiuAeHHhGvWLamUOtbJQbShAA',
    appId: '1:532983348001:ios:4665adac5d0e733f76dc60',
    messagingSenderId: '532983348001',
    projectId: 'reminderapp-6ffe3',
    storageBucket: 'reminderapp-6ffe3.appspot.com',
    iosBundleId: 'com.example.suplisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB56eLI1PiuAeHHhGvWLamUOtbJQbShAA',
    appId: '1:532983348001:ios:4665adac5d0e733f76dc60',
    messagingSenderId: '532983348001',
    projectId: 'reminderapp-6ffe3',
    storageBucket: 'reminderapp-6ffe3.appspot.com',
    iosBundleId: 'com.example.suplisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp50kUKBQhPyawY24cMEYbKL_QNZ_9mvg',
    appId: '1:532983348001:web:6e537fea8e5fde6876dc60',
    messagingSenderId: '532983348001',
    projectId: 'reminderapp-6ffe3',
    authDomain: 'reminderapp-6ffe3.firebaseapp.com',
    storageBucket: 'reminderapp-6ffe3.appspot.com',
    measurementId: 'G-MCMVEKC54G',
  );
}
